[package]
name = "string-sum"
version = "0.1.0"
edition = "2018"

[lib]
name = "rust"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.42"

[dependencies.pyo3]
version = "0.14.2"
features = ["extension-module"]
