[package]
name = "gettext"
version = "0.1.0"
authors = ["Miklos Vajna <vmiklos@collabora.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gettext = "0.4.0"
