[package]
name = "yattag"
version = "0.1.0"
authors = ["Miklos Vajna <vmiklos@collabora.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-escape = "0.2.9"
