[package]
name = "wsgi"
version = "0.1.0"
authors = ["Miklos Vajna <vmiklos@collabora.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.2.1"
