name: tests
on:
  push:
    branches-ignore:
      - 'private/**'
  pull_request:
    branches-ignore:
      - 'private/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.53.0
      - name: Run cargo test
        run: |
          cargo test
